"""update

Revision ID: e677b6362240
Revises: 8b3a7e1864c9
Create Date: 2022-10-30 21:11:12.529245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e677b6362240'
down_revision = '8b3a7e1864c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'sign', ['sign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'sign_id')
    # ### end Alembic commands ###
